{% set version = "2.1.0" %}

package:
  name: expat
  version: {{ version }}

source:
  fn: expat-{{ version }}.tar.bz2
  url: http://downloads.sourceforge.net/project/expat/expat/{{ version }}/expat-{{ version }}.tar.gz
  sha256: 823705472f816df21c8f6aa026dd162b280806838bb55b3432b0fb1fcca7eb86

build:
  number: 2
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - cmake  # [win]
    - python  # [win]
    - msinttypes  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - xmlwf -h

about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_file: COPYING
  summary: Expat XML parser library in C

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
