{% set version = "2.4.8" %}
{% set ver = version|replace(".", "_") %}

package:
  name: expat
  version: {{ version }}

source:
  url: https://github.com/libexpat/libexpat/releases/download/R_{{ ver }}/expat-{{ version }}.tar.bz2
  sha256: a247a7f6bbb21cf2ca81ea4cbb916bfb9717ca523631675f99b3d4a5678dcd16

build:
  number: 0
  run_exports:
    # changes soname at major versions, default settings OK
    # https://abi-laboratory.pro/tracker/timeline/expat/
    - {{ pin_subpackage('expat') }}

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and vc<14]

test:
  commands:
    - xmlwf -h

about:
  home: https://libexpat.github.io
  license: MIT
  license_family: MIT
  # Note that the file is in a subdirectory expat/COPYING the expat is in a subdirectory
  license_file: COPYING
  summary: 'Expat XML parser library in C'
  dev_url: https://github.com/libexpat/libexpat
  doc_url: https://github.com/libexpat/libexpat/tree/master/expat/doc

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - mingwandroid
    - msarahan
    - scopatz
