{% set version = "2.2.4" %}

package:
  name: expat
  version: {{ version }}

source:
  fn: expat-{{ version }}.tar.bz2
  url: http://downloads.sourceforge.net/project/expat/expat/{{ version }}/expat-{{ version }}.tar.bz2
  sha256: 03ad85db965f8ab2d27328abcf0bc5571af6ec0a414874b2066ee3fdd372019e
  patches:
    # Fixes https://github.com/conda-forge/expat-feedstock/pull/11#issuecomment-312501043
    utf8.patch

build:
  number: 2
  features:
    - vc{{ vc }}  # [win]
  run_exports:
    # changes soname at major versions, default settings OK
    #    https://abi-laboratory.pro/tracker/timeline/expat/
    - {{ pin_subpackage('expat') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - msinttypes  # [win and vc<14]

test:
  commands:
    - xmlwf -h
    - conda inspect linkages -p $PREFIX expat  # [not win]
    - conda inspect objects -p $PREFIX expat  # [osx]

about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_file: COPYING
  summary: 'Expat XML parser library in C.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - mingwandroid
    - msarahan
