{% set version = "2.2.1" %}

package:
  name: expat
  version: {{ version }}

source:
  fn: expat-{{ version }}.tar.bz2
  url: http://downloads.sourceforge.net/project/expat/expat/{{ version }}/expat-{{ version }}.tar.bz2
  sha256: 1868cadae4c82a018e361e2b2091de103cd820aaacb0d6cfa49bd2cd83978885
  patches:
    # Fixes https://github.com/conda-forge/expat-feedstock/pull/11#issuecomment-312501043
    utf8.patch

build:
  number: 2
  features:
    - vc{{ vc }}  # [win]
  run_exports:
    # changes SONAME at major rev.  Default behavior OK.
    #   https://abi-laboratory.pro/tracker/timeline/expat/
    - {{ pin_subpackage('expat') }}

requirements:
  build:
    - cmake  # [win]
    - msinttypes  # [win and vc<14]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - xmlwf -h
    - conda inspect linkages -p $PREFIX expat  # [not win]
    - conda inspect objects -p $PREFIX expat  # [osx]

about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_file: COPYING
  summary: 'Expat XML parser library in C.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - mingwandroid
    - msarahan
